AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sum-app

  Sample SAM Template for sum-app

Globals:
  Function:
    Timeout: 10

Resources:
  SumAppFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: out/.
      Handler: main
      Runtime: go1.x
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess

Outputs:
  SumAppFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt SumAppFunction.Arn
  SumAppFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt SumAppFunctionRole.Arn
